### PR TITLE
Add context menu

### PR DESCRIPTION
**Pull request by fallroot**
It will be useful for circumstance that can't use browser action like popup window.

### CODE REVIEW

**Comment by fallroot** [comment]
I signed it!

**Comment by beaufortfrancois** [comment]
Thanks for the PR @fallroot.
Can you tell me more about your use cases?
Why not use keyboard shortcut "Alt + P" to trigger it?

**Comment by fallroot** [comment]
It is just another option. Sometimes I want to read web pages with mouse only and some page use popup window for video player.

**Comment by fallroot** [comment]
Ok, I think that let this extension be remained with minimal features as reference is not bad.

**Pull request closed without merging**
